{% set name = "voila" %}
{% set version = "0.2.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: be0612f95b87f99c6caaac70cd7af15b5b9331a985d0f95503f6ebc17a083c8f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - voila = voila.app:main

requirements:
  host:
    - python >=3.6
    - pip
    - nodejs <16
    - jupyter-packaging >=0.10,<1
  run:
    - python >=3.6
    - nbconvert >=6.0.0,<7
    - jupyter_client >=6.1.3,<7
    - jupyter_server >=0.3.0,<2
    - nbclient >=0.4.0,<0.6

test:
  imports:
    - voila
  commands:
    - voila --help


about:
  home: https://github.com/voila-dashboards/voila
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Rendering of live Jupyter notebooks with interactive widgets
  description: |
    Voila serves live Jupyter notebooks including Jupyter interactive widgets.
    Unlike the usual HTML-converted notebooks, each user connecting to the
    Voila tornado application is associated with a dedicated Jupyter kernel
    which can execute triggered by Jupyter interactive widgets.

    By default, voila disallows execute requests from the front-end, disabling
    the ability to execute arbitrary code.
  dev_url: https://github.com/voila-dashboards/voila

extra:
  recipe-maintainers:
    - SylvainCorlay
    - maartenbreddels
    - JohanMabille
    - jtpio
