{% set name = "voila" %}
{% set version = "0.5.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 12057fe409298024a104b75bbb1050576b89f42fe6e8fead8f5d1f79ace66b19

build:
  number: 0
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vvv
  entry_points:
    - voila = voila.app:main

requirements:
  host:
    - python
    - pip
    - hatchling >=1.8.1
    - jupyterlab >=4.0,<5
    - jupyter_core
    - hatch-jupyter-builder >=0.5.3
  run:
    - python
    - jupyter_client >=7.4.4,<9
    - jupyter_core >=4.11.0
    - jupyter_server >=1.18,<3
    - jupyterlab_server >=2.3.0,<3
    - nbclient >=0.4.0
    - nbconvert >=6.4.5,<8
    - traitlets >=5.0.3,<6
    - websockets >=9.0
  run_constrained:
    - ipywidgets >=7  # set by core developer on cf recipe.

# E tornado.httpclient.HTTPClientError: HTTP 404: Not Found
{% set deselect_test = " --deselect=tests/app/static_files_test.py::test_static_file_other_template" %}
# >       assert response_lab.body.decode("utf-8") != response_test_template.body.decode(# "utf-8"# )
# E       assert 'var _JUPYTERLAB;(()=>{var e,t,r,l,n,a,o,i,
{% set deselect_test = deselect_test + " --deselect=tests/app/static_files_test.py::test_static_file_override" %}
# E       tornado.simple_httpclient.HTTPTimeoutError: Timeout during request
{% set deselect_test = deselect_test + " --deselect=tests/app/preprocessor_test.py::test_markdown_preprocessor" %}
{% set deselect_test = deselect_test + " --deselect=tests/app/template_cli_test.py::test_template_test" %}
{% set deselect_test = deselect_test + " --deselect=tests/app/config_paths_test.py::test_template" %}
{% set deselect_test = deselect_test + " --deselect=tests/app/config_paths_test.py::test_template_test" %}
{% set deselect_test = deselect_test + " --deselect=tests/app/config_paths_test.py::test_template_override" %}
{% set deselect_test = deselect_test + " --deselect=tests/app/template_arg_test.py::test_template" %}
{% set deselect_test = deselect_test + " --deselect=tests/app/template_config_file_test.py::test_template_test" %}
# tests randomly hanging on CI
{% set ignore_test = " --ignore=tests/server" %}

test:
  source_files:
    - tests
    - share 
  imports:
    - voila
  requires:
    - pip
    - pytest
    - ipywidgets
    - ipykernel
    - pytest-tornasync
    - papermill
    - matplotlib
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - voila --help
    # OSX tests randomly crash on CI due to unknown reason, also failing due to 'zmq.error.ZMQError: Too many open files'
    - pytest -v tests {{ deselect_test }}  # [not osx]

about:
  home: https://github.com/voila-dashboards/voila
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Rendering of live Jupyter notebooks with interactive widgets
  description: |
    Voila serves live Jupyter notebooks including Jupyter interactive widgets.
    Unlike the usual HTML-converted notebooks, each user connecting to the
    Voila tornado application is associated with a dedicated Jupyter kernel
    which can execute triggered by Jupyter interactive widgets.

    By default, voila disallows execute requests from the front-end, disabling
    the ability to execute arbitrary code.
  dev_url: https://github.com/voila-dashboards/voila
  doc_url: https://voila.readthedocs.io

extra:
  recipe-maintainers:
    - SylvainCorlay
    - maartenbreddels
    - JohanMabille
    - jtpio
    - trungleduc
    - martinRenou
