{% set name = "voila" %}
{% set version = "0.1.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 64443e235b82a17e5a0417ba0d69df1f21441de785944b917ba192f6313995f0

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  entry_points:
    - voila = voila.app:main

requirements:
  host:
    - python >=3
    - pip
    - nodejs
  run:
    - python >=3
    - nbconvert >=5.5.0,<6
    - jupyter_server >=0.1.0,<0.2.0
    - jupyterlab_pygments >=0.1.0,<0.2

test:
  imports:
    - voila
  commands:
    - voila --help

about:
  home: http://github.com/QuantStack/voila
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Rendering of live Jupyter notebooks with interactive widgets'
  description: |
    Voila serves live Jupyter notebooks including Jupyter interactive widgets.
    Unlike the usual HTML-converted notebooks, each user connecting to the
    Voila tornado application is associated with a dedicated Jupyter kernel
    which can execute triggered by Jupyter interactive widgets.

    By default, voila disallows execute requests from the front-end, disabling
    the ability to execute arbitrary code.
  dev_url: https://github.com/QuantStack/voila

extra:
  recipe-maintainers:
    - SylvainCorlay
    - maartenbreddels
    - JohanMabille
    - jtpio
