{% set name = "voila" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6f44312b265de1cc43717406635979276e3210269dcd67e760eca1be5be1d3c7

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  entry_points:
    - voila = voila.app:main

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - nbconvert >=5.4.0,<6
    - jupyter_server ==0.0.2

test:
  imports:
    - voila
  commands:
    - voila --help

about:
  home: http://github.com/QuantStack/voila
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Rendering of live Jupyter notebooks with interactive widgets'
  description: |
    Voila serves live Jupyter notebooks including Jupyter interactive widgets.
    Unlike the usual HTML-converted notebooks, each user connecting to the
    Voila tornado application gets a dedicated Jupyter kernel which can execute
    the callbacks to changes in Jupyter interactive widgets.

    By default, voila disallows execute requests from the front-end, disabling
    the ability to execute arbitrary code.
    By defaults, voila runs with the strip_source option, which strips out the
    input cells from the rendered notebook.
  dev_url: https://github.com/QuantStack/voila

extra:
  recipe-maintainers:
    - SylvainCorlay
    - maartenbreddels
    - JohanMabille
