travis:
  secure:
    BINSTAR_TOKEN: z4cEFoBpn7QX/P3xgjGeC/XtY7TgxYY+CNHSi/nDh5S1WBvSMVP1z+0nuHlU2H6VkSDQYc+abnb+Km4RlWxJ3F2VE3UxvFgYmvWGXcC6MOWIkD+EO9/fI+ujLHeHgSmp4N+22JvUThoBNKcKNypcXuP9xQzPizbtHvaFLcCbLv18FK8CSBDJ49XBLJKbCiAHqVIghyVLdWlb71RkhX9ob35OdcwFYRBf1wosXzE6m/YzgXuYUGA4XilHnAtaAXqOm0jMPiCieQoI2SYTjYU2h2MmSCATKRs5SD/D+ZPg9iuk9poefQ8I5TkdmJJ/o8GGYK5LezmSWEF6jDX/Bz7g2Vy5AY74UGcX56ZNavkzNgwDGHTt1r/Tqe7Rji0tcrl5rdhrqqUympoQDRgJkacI3bQ+8Sd0GpokomW1vgaS2W2PxnFSd+IpAXvK4FHoZyR0BDK6I5cqMmRxIMnUqv/zoFn97vbVSYltCEYBNkREbdgzYOe1tBACmWDQXn+McM6CF9ACu7x3G/amj9s+H/5rMDNa9W+rXcATv5QM8aWxfRf60I+natGbPBq4ODSdCIp1uHP+15DUPReKc0B5Sx6HDGnod2FGNNMWdmlHM/08Zmhiq0uqL8MpJ3WQIxsaK+aYREf5mbFo/2lTcO1FLa4UyttwCIfUr9Mt5/6m4GrQAJ8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
